// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kokkgedkjuhjvpxwemli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtva2tnZWRranVoanZweHdlbWxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMjA3OTksImV4cCI6MjA2NTU5Njc5OX0.QJse3EBLb_YZd7RrO2FxKKfGSbY1WhJoUrki8LCCMlU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);